package Main;

import java.awt.CardLayout;
import javax.swing.UIManager;

/**
 *
 * @author Wiguna R
 */
public class FormContainer extends javax.swing.JFrame {
    private final static String PANEL_BUKU = "Panel Buku";
    private final static String PANEL_DASHBOARD = "Panel Dashboard";
    private final static String PANEL_SEWA = "Panel Penyewaan";
    private final static String PANEL_KEMBALI = "Panel Pengembalian";
    private final static String PANEL_SETTING = "Panel Setting";
    private CardLayout cardLayout;
    PanelBuku buku;
    PanelDashboard dashboard;
    PanelSewa sewa;
    PanelKembali kembali;
    PanelUsers users;
    
    public String username, role;
    /**
     * Creates new form FormBuku
     * @param username
     * @param role
     */
    public FormContainer(String username, String role) {
        initComponents();
        this.username = username;
        
        this.buku      = new PanelBuku(this);
        this.dashboard = new PanelDashboard(this);
        this.sewa      = new PanelSewa(this);
        this.kembali   = new PanelKembali(this);
        this.users     = new PanelUsers(this);
        
        panelContainer.add(this.dashboard, PANEL_DASHBOARD);
        panelContainer.add(this.buku, PANEL_BUKU);
        panelContainer.add(this.sewa, PANEL_SEWA);
        panelContainer.add(this.kembali, PANEL_KEMBALI);
        panelContainer.add(this.users, PANEL_SETTING);
        
        cardLayout = (CardLayout)(panelContainer.getLayout());
        
        if(role.equals("Kasir")){
            btnBuku.setVisible(false);
            btnSetting.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        labelSubJudul = new javax.swing.JLabel();
        btnSetting = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnBuku = new javax.swing.JButton();
        btnPenyewaan = new javax.swing.JButton();
        btnPengembalian = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        panelContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelSidebar.setBackground(new java.awt.Color(32, 33, 35));
        panelSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelJudul.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(57, 113, 177));
        labelJudul.setText("sysbook");
        panelSidebar.add(labelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        labelSubJudul.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelSubJudul.setForeground(new java.awt.Color(255, 255, 255));
        labelSubJudul.setText("Book Management System");
        panelSidebar.add(labelSubJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        btnSetting.setBackground(new java.awt.Color(32, 33, 35));
        btnSetting.setForeground(new java.awt.Color(255, 255, 255));
        btnSetting.setText("Setting User");
        btnSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });
        panelSidebar.add(btnSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 240, 50));

        btnDashboard.setBackground(new java.awt.Color(32, 33, 35));
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        panelSidebar.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 50));

        btnBuku.setBackground(new java.awt.Color(32, 33, 35));
        btnBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnBuku.setText("Buku");
        btnBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukuActionPerformed(evt);
            }
        });
        panelSidebar.add(btnBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 50));

        btnPenyewaan.setBackground(new java.awt.Color(32, 33, 35));
        btnPenyewaan.setForeground(new java.awt.Color(255, 255, 255));
        btnPenyewaan.setText("Penyewaan Buku");
        btnPenyewaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenyewaanActionPerformed(evt);
            }
        });
        panelSidebar.add(btnPenyewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 240, 50));

        btnPengembalian.setBackground(new java.awt.Color(32, 33, 35));
        btnPengembalian.setForeground(new java.awt.Color(255, 255, 255));
        btnPengembalian.setText("Pengembalian Buku");
        btnPengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengembalianActionPerformed(evt);
            }
        });
        panelSidebar.add(btnPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 240, 50));

        btnLogout.setBackground(new java.awt.Color(126, 87, 194));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        panelSidebar.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 240, 50));

        panelContainer.setMinimumSize(new java.awt.Dimension(915, 697));
        panelContainer.setRequestFocusEnabled(false);
        panelContainer.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
            .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukuActionPerformed
        try {
            cardLayout.show(panelContainer, PANEL_BUKU);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBukuActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        try {
            cardLayout.show(panelContainer, PANEL_DASHBOARD);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnPenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenyewaanActionPerformed
        try {
            cardLayout.show(panelContainer, PANEL_SEWA);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPenyewaanActionPerformed

    private void btnPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengembalianActionPerformed
        try {
            cardLayout.show(panelContainer, PANEL_KEMBALI);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPengembalianActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        try {
            cardLayout.show(panelContainer, PANEL_SETTING);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Main main = new Main();
        this.username = "";
        this.role     = "";
        
        this.dispose();
        main.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    
    
    
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
//            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormContainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new FormContainer().setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuku;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPengembalian;
    private javax.swing.JButton btnPenyewaan;
    private javax.swing.JButton btnSetting;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelSubJudul;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
