package Main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Wiguna R
 */
public class PanelDashboard extends javax.swing.JPanel {
    FormContainer container;
    
    Connection conn       = null;
    ResultSet rs          = null;
    PreparedStatement pst = null;
    
    private int jumBuku;
    private String username;
    /**
     * Creates new form FormDashboard
     * @param container
     */
    public PanelDashboard(FormContainer container) {
        initComponents();
        this.container = container;
        this.conn      = MySQLConnection.ConnectDb();
        username = container.username;
        textUsername.setText(username);
        countBook();
        countPenyewaan("Pinjam");
        countPenyewaan("Kembali");
        countKeuangan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        textUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelBuku = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelPeminjaman = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelPengembalian = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        labelPencarian = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        labelDenda = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        labelPemasukan = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        textPenyewa = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        textPengembalian = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        textBuku = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        textPencarian = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        textDenda = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        textPemasukan = new javax.swing.JLabel();

        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textUsername.setBackground(new java.awt.Color(0, 0, 0));
        textUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textUsername.setForeground(new java.awt.Color(57, 113, 177));
        textUsername.setText("username");
        panelHeader.add(textUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, 30));

        jLabel2.setText("You logged in as ");
        panelHeader.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, 30));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        panelHeader.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(226, 65));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        labelBuku.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelBuku.setForeground(new java.awt.Color(57, 113, 177));
        labelBuku.setText("Buku");
        jPanel1.add(labelBuku, new java.awt.GridBagConstraints());

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        labelPeminjaman.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelPeminjaman.setForeground(new java.awt.Color(57, 113, 177));
        labelPeminjaman.setText("Penyewa");
        jPanel2.add(labelPeminjaman, new java.awt.GridBagConstraints());

        jPanel3.setBackground(new java.awt.Color(32, 33, 35));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        labelPengembalian.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelPengembalian.setForeground(new java.awt.Color(57, 113, 177));
        labelPengembalian.setText("Pengembalian");
        jPanel3.add(labelPengembalian, new java.awt.GridBagConstraints());

        jPanel7.setBackground(new java.awt.Color(32, 33, 35));
        jPanel7.setMinimumSize(new java.awt.Dimension(226, 65));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        labelPencarian.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelPencarian.setForeground(new java.awt.Color(57, 113, 177));
        labelPencarian.setText("<Reversed>");
        jPanel7.add(labelPencarian, new java.awt.GridBagConstraints());

        jPanel8.setBackground(new java.awt.Color(32, 33, 35));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        labelDenda.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelDenda.setForeground(new java.awt.Color(57, 113, 177));
        labelDenda.setText("Denda");
        jPanel8.add(labelDenda, new java.awt.GridBagConstraints());

        jPanel9.setBackground(new java.awt.Color(32, 33, 35));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        labelPemasukan.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelPemasukan.setForeground(new java.awt.Color(57, 113, 177));
        labelPemasukan.setText("Total Pemasukan");
        jPanel9.add(labelPemasukan, new java.awt.GridBagConstraints());

        jPanel4.setLayout(new java.awt.GridBagLayout());

        textPenyewa.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        textPenyewa.setText("100");
        jPanel4.add(textPenyewa, new java.awt.GridBagConstraints());

        jPanel5.setLayout(new java.awt.GridBagLayout());

        textPengembalian.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        textPengembalian.setText("111");
        jPanel5.add(textPengembalian, new java.awt.GridBagConstraints());

        jPanel6.setLayout(new java.awt.GridBagLayout());

        textBuku.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        textBuku.setText("100");
        jPanel6.add(textBuku, new java.awt.GridBagConstraints());

        jPanel10.setLayout(new java.awt.GridBagLayout());

        textPencarian.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        textPencarian.setText("0");
        jPanel10.add(textPencarian, new java.awt.GridBagConstraints());

        jPanel11.setLayout(new java.awt.GridBagLayout());

        textDenda.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        textDenda.setText("111");
        jPanel11.add(textDenda, new java.awt.GridBagConstraints());

        jPanel12.setLayout(new java.awt.GridBagLayout());

        textPemasukan.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        textPemasukan.setText("Rp 10000");
        jPanel12.add(textPemasukan, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addGap(93, 93, 93)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        countBook();
        countPenyewaan("Pinjam");
        countPenyewaan("Kembali");
        countKeuangan();
    }//GEN-LAST:event_btnRefreshActionPerformed

    public void countBook(){
        String query = "SELECT count(*) FROM tbl_buku";
        
        try {
            pst = conn.prepareStatement(query);
            rs  = pst.executeQuery();
            
            while(rs.next()){
                jumBuku = rs.getInt(1);
            }
            textBuku.setText(jumBuku + "");
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR : terjadi kesalahan sistem.");
        }
    }
    
    public void countPenyewaan(String status){
        int jumlah = 0;
        String sql = "SELECT count(*) FROM tbl_sewa WHERE sew_status = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, status);
            rs = pst.executeQuery();
            
            while(rs.next()){
                jumlah = rs.getInt(1);
            }
            
            if(status.equals("Pinjam")){
                textPenyewa.setText(jumlah + "");
            }else{
                textPengembalian.setText(jumlah + "");
            }
            
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR : Terjadi kesalahan sistem saat menghitung banyak peminjam");
        }
    }
    
    public void countKeuangan(){
        int totalPemasukan = 0, totalDenda = 0;
        String sql = "SELECT sew_totalHarga, sew_denda FROM tbl_sewa";
        
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                totalPemasukan += rs.getInt("sew_totalHarga");
                totalDenda += rs.getInt("sew_denda");
            }
            
            textPemasukan.setText("Rp " + totalPemasukan);
            textDenda.setText("Rp " + totalDenda);
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR : Terjadi kesalahan sistem saat menghitung keuangan");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelBuku;
    private javax.swing.JLabel labelDenda;
    private javax.swing.JLabel labelPemasukan;
    private javax.swing.JLabel labelPeminjaman;
    private javax.swing.JLabel labelPencarian;
    private javax.swing.JLabel labelPengembalian;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JLabel textBuku;
    private javax.swing.JLabel textDenda;
    private javax.swing.JLabel textPemasukan;
    private javax.swing.JLabel textPencarian;
    private javax.swing.JLabel textPengembalian;
    private javax.swing.JLabel textPenyewa;
    private javax.swing.JLabel textUsername;
    // End of variables declaration//GEN-END:variables
}
