package Main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PanelKembali extends javax.swing.JPanel {
    FormContainer container;
    
    Connection conn       = null;
    ResultSet rs          = null;
    PreparedStatement pst = null;
    
    DefaultTableModel defaultTableSewa, defaultTableInvoice;
    
    private int id;
    /**
     * Creates new form PanelPinjam
     * @param container
     */
    public PanelKembali(FormContainer container) {
        initComponents();
        this.container = container;
        this.conn      = MySQLConnection.ConnectDb();
        defaultTableSewa = new DefaultTableModel(new String[]{"No.", "Nama Penyewa", "Judul Buku", "Lama Peminjaman", "Tanggal Pinjam", "Tanggal Kembali", "Harga Sewa", "Denda"}, 0);
        defaultTableInvoice = new DefaultTableModel(new String[]{"ID Buku", "Judul Buku", "Lama Peminjaman", "Tanggal Kembali", "Denda"}, 0);
        tblInvoice1.setModel(defaultTableInvoice);
        getAllPesewa();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inNamaPeminjam = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCari = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnKembali = new javax.swing.JButton();
        labelJudul4 = new javax.swing.JLabel();
        textHarga = new javax.swing.JLabel();
        panelInvoice1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInvoice1 = new javax.swing.JTable();
        panelTable = new javax.swing.JLayeredPane();
        panelTableHeader = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesewa = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(910, 697));

        jPanel2.setMinimumSize(new java.awt.Dimension(450, 55));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Pengembalian Buku");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        inNamaPeminjam.setBorder(null);
        inNamaPeminjam.setCaretColor(new java.awt.Color(255, 255, 255));

        labelNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNama.setForeground(new java.awt.Color(57, 113, 177));
        labelNama.setText("Nama Peminjam");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(btnReset))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Invoice");
        jPanel5.add(jLabel2, new java.awt.GridBagConstraints());

        btnKembali.setText("Kembalikan");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        labelJudul4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelJudul4.setForeground(new java.awt.Color(57, 113, 177));
        labelJudul4.setText("Total Denda");

        textHarga.setText("Rp 0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudul4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220)
                .addComponent(btnKembali)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(labelJudul4)
                    .addComponent(textHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelInvoice1.setMaximumSize(new java.awt.Dimension(518, 167));
        panelInvoice1.setMinimumSize(new java.awt.Dimension(518, 167));

        tblInvoice1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode", "Judul Buku", "Lama Peminjaman", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblInvoice1);

        javax.swing.GroupLayout panelInvoice1Layout = new javax.swing.GroupLayout(panelInvoice1);
        panelInvoice1.setLayout(panelInvoice1Layout);
        panelInvoice1Layout.setHorizontalGroup(
            panelInvoice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvoice1Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addGap(0, 0, 0))
        );
        panelInvoice1Layout.setVerticalGroup(
            panelInvoice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(panelInvoice1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(panelInvoice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Daftar Penyewa");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        panelTableHeader.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelTableHeader.setLayer(btnRefresh, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelTableHeaderLayout = new javax.swing.GroupLayout(panelTableHeader);
        panelTableHeader.setLayout(panelTableHeaderLayout);
        panelTableHeaderLayout.setHorizontalGroup(
            panelTableHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addContainerGap())
        );
        panelTableHeaderLayout.setVerticalGroup(
            panelTableHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTableHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(btnRefresh))
                .addGap(17, 17, 17))
        );

        tblPesewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                " No.", "Nama Peminjam", "Judul Buku", "Tanggal Pinjam", "Tanggal Kembali", "Denda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPesewa);

        panelTable.setLayer(panelTableHeader, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelTable.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(panelTableHeader)
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTableHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelTable))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        getAllPesewa();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
       String nama = inNamaPeminjam.getText();
       cariPeminjam(nama);
       hitungTotalDenda();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String nama = inNamaPeminjam.getText();
        int denda, id, stok;
        for (int i = 0; i < tblInvoice1.getRowCount(); i++) {
            denda = Integer.parseInt(tblInvoice1.getValueAt(i, 4) + "");
            id    = Integer.parseInt(tblInvoice1.getValueAt(i, 0) + "");
            
            stok = getBukuStok(id);
            stok = stok + 1;
            updatePesewa(nama, denda, id);
            updateBukuStok(id, stok);
        }
        getAllPesewa();
        defaultTableInvoice.setRowCount(0);
    }//GEN-LAST:event_btnKembaliActionPerformed

    public void getAllPesewa(){
        defaultTableSewa.setRowCount(0);
        String nama, judul, tglPinjam, tglKembali;
        int no = 1, lamaPeminjaman, hargaSewa, denda;
        long tanggalPinjam, tanggalKembali;
        long tanggalSekarang = System.currentTimeMillis() / 1000L;
        String sql = "SELECT sew.sew_nama as sewNama, buk.buk_judul as bukJudul, "
                + "sew.sew_lamaPeminjaman as sewLamaPeminjaman, sew.sew_tanggalPinjam as sewTanggalPeminjaman,"
                + "sew.sew_tanggalKembali as sewTanggalKembali, sew.sew_totalHarga as sewTotalHarga,"
                + "sew.sew_denda as sewDenda"
                + " FROM tbl_sewa as sew"
                + " JOIN tbl_buku as buk ON buk.buk_id = sew.buk_id"
                + " WHERE sew.sew_status = 'Pinjam'";
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                nama           = rs.getString("sewNama");
                judul          = rs.getString("bukJudul");
                lamaPeminjaman = rs.getInt("sewLamaPeminjaman");
                tanggalPinjam  = rs.getLong("sewTanggalPeminjaman");
                tanggalKembali = rs.getLong("sewTanggalKembali");
                hargaSewa      = rs.getInt("sewTotalHarga");
                denda          = rs.getInt("sewDenda");
                
                tglPinjam  = dateFormat.format(new Date(tanggalPinjam * 1000L));
                tglKembali = dateFormat.format(new Date(tanggalKembali * 1000L));
                
                if((tanggalSekarang - tanggalKembali) > 86400){
                    double jumlahDenda = (tanggalSekarang - tanggalKembali) / 86400;
                    denda = (int) (hargaSewa * Math.floor(jumlahDenda));
                }
                
                defaultTableSewa.addRow(new Object[]{no, nama, judul, lamaPeminjaman, tglPinjam, tglKembali, hargaSewa, denda});
                no++;
            }
            tblPesewa.setModel(defaultTableSewa);
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR : gagal mengambil data pesewa");
        }
    }
    
    public void cariPeminjam(String nama){
        defaultTableSewa.setRowCount(0);
        defaultTableInvoice.setRowCount(0);
        String judul, tglPinjam, tglKembali;
        int no = 1, lamaPeminjaman, hargaSewa, denda, id;
        long tanggalPinjam, tanggalKembali;
        long tanggalSekarang = System.currentTimeMillis() / 1000L;
        String sql = "SELECT sew.sew_nama as sewNama, buk.buk_judul as bukJudul, "
                + "sew.sew_lamaPeminjaman as sewLamaPeminjaman, sew.sew_tanggalPinjam as sewTanggalPeminjaman,"
                + "sew.sew_tanggalKembali as sewTanggalKembali, sew.sew_totalHarga as sewTotalHarga,"
                + "sew.sew_denda as sewDenda, sew.buk_id as bukId"
                + " FROM tbl_sewa as sew"
                + " JOIN tbl_buku as buk ON buk.buk_id = sew.buk_id"
                + " WHERE sew.sew_nama LIKE ?";
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + nama + "%");
            rs = pst.executeQuery();
            
            while(rs.next()){
                nama           = rs.getString("sewNama");
                judul          = rs.getString("bukJudul");
                lamaPeminjaman = rs.getInt("sewLamaPeminjaman");
                tanggalPinjam  = rs.getLong("sewTanggalPeminjaman");
                tanggalKembali = rs.getLong("sewTanggalKembali");
                hargaSewa      = rs.getInt("sewTotalHarga");
                denda          = rs.getInt("sewDenda");
                id             = rs.getInt("bukId");
                
                tglPinjam  = dateFormat.format(new Date(tanggalPinjam * 1000L));
                tglKembali = dateFormat.format(new Date(tanggalKembali * 1000L));
                
                if((tanggalSekarang - tanggalKembali) > 86400){
                    double jumlahDenda = (tanggalSekarang - tanggalKembali) / 86400;
                    denda = (int) (hargaSewa * Math.floor(jumlahDenda));
                }
                
                defaultTableSewa.addRow(new Object[]{no, nama, judul, lamaPeminjaman, tglPinjam, tglKembali, hargaSewa, denda});
                defaultTableInvoice.addRow(new Object[]{id, judul, lamaPeminjaman, tglKembali, denda});
                no++;
            }
            tblPesewa.setModel(defaultTableSewa);
            tblInvoice1.setModel(defaultTableInvoice);
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR : gagal mengambil data pesewa");
        }
    }
    
    public void updatePesewa(String nama, int denda, int id){
        String sql = "UPDATE tbl_sewa SET sew_status = 'Kembali', sew_denda = ? WHERE sew_nama LIKE ? AND buk_id = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, denda);
            pst.setString(2, "%" + nama + "%");
            pst.setInt(3, id);
            
            if(pst.executeUpdate() == 0){
                JOptionPane.showMessageDialog(null, "Buku gagal dikembalikan", "Pengembalian buku", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR : Terjadi kesalahan sistem saat pengembalian buku");
        }
    }
    
    public int getBukuStok(int id){
        int stok = 0;
        String sql = "SELECT buk_stok FROM tbl_buku WHERE buk_id = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            rs = pst.executeQuery();
            
            while(rs.next()){
                stok = rs.getInt("buk_stok");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR : terjadi kesalahan saat mengambil stok buku");
        }
        return stok;
    }
    
    public void updateBukuStok(int id, int stok){
        String sql = "UPDATE tbl_buku SET buk_stok = ? WHERE buk_id = ?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setInt(1, stok);
            pst.setInt(2, id);
            
            if(pst.executeUpdate() != 0){
                System.out.println("Update stok berhasil");
            }else{
                System.out.println("Update stok gagal");
            }
        }catch(SQLException ex){
            ex.printStackTrace();
            System.out.println("ERROR : terjadi kesalahan sistem saat update stok buku");
        }
    }
    
    public void hitungTotalDenda(){
        int total = 0;
        int selectedRowDenda;
        for (int i = 0; i < tblInvoice1.getRowCount(); i++) {
            selectedRowDenda = Integer.parseInt(tblInvoice1.getValueAt(i, 4) + "");
            total = selectedRowDenda + total;
            textHarga.setText("Rp " + total);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField inNamaPeminjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelJudul4;
    private javax.swing.JLabel labelNama;
    private javax.swing.JPanel panelInvoice1;
    private javax.swing.JLayeredPane panelTable;
    private javax.swing.JLayeredPane panelTableHeader;
    private javax.swing.JTable tblInvoice1;
    private javax.swing.JTable tblPesewa;
    private javax.swing.JLabel textHarga;
    // End of variables declaration//GEN-END:variables
}
